### ISSUE TITLE
Panic on Hugo

### ISSUE THREAD

**Issue by bep** [mvdan/interfacer#6]
https://github.com/spf13/hugo

```
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/mvdan/interfacer.(*visitor).addUsed(0xc82b76bf40, 0xc8206f6c00, 0x4, 0x64c2b8, 0x422ac0)
	/Users/bep/go/src/github.com/mvdan/interfacer/check.go:229 +0x2f5
github.com/mvdan/interfacer.(*visitor).Visit(0xc82b76bf40, 0x7cbba0, 0xc820b82a40, 0x0, 0x0)
	/Users/bep/go/src/github.com/mvdan/interfacer/check.go:273 +0x980
go/ast.Walk(0x7cb848, 0xc82b76bf40, 0x7cbba0, 0xc820b82a40)
	/usr/local/go/src/go/ast/walk.go:52 +0x56
go/ast.walkStmtList(0x7cb848, 0xc82b76bf40, 0xc8204c1a00, 0x8, 0x8)
	/usr/local/go/src/go/ast/walk.go:32 +0xd5
go/ast.Walk(0x7cb848, 0xc82b76bf40, 0x6c66e8, 0xc8206116b0)
	/usr/local/go/src/go/ast/walk.go:224 +0x3e19
go/ast.Walk(0x7cb848, 0xc82b76bf40, 0x7cbab0, 0xc8206f6dc0)
	/usr/local/go/src/go/ast/walk.go:98 +0x31f7
go/ast.Walk(0x7cb848, 0xc82b76bf40, 0x7cba80, 0xc8206116e0)
	/usr/local/go/src/go/ast/walk.go:151 +0x1593
go/ast.walkExprList(0x7cb848, 0xc82b76bf40, 0xc820b82500, 0x4, 0x4)
	/usr/local/go/src/go/ast/walk.go:26 +0xd5
go/ast.Walk(0x7cb848, 0xc82b76bf40, 0x7cba50, 0xc820b82bc0)
	/usr/local/go/src/go/ast/walk.go:104 +0xdb2
go/ast.Walk(0x7cb848, 0xc82b76bf40, 0x7cba20, 0xc820b5b020)
	/usr/local/go/src/go/ast/walk.go:143 +0x17ff
go/ast.walkExprList(0x7cb848, 0xc82b76bf40, 0xc8206f6dd0, 0x1, 0x1)
	/usr/local/go/src/go/ast/walk.go:26 +0xd5
go/ast.Walk(0x7cb848, 0xc82b76bf40, 0x7cb9f0, 0xc820920000)
	/usr/local/go/src/go/ast/walk.go:308 +0xf63
go/ast.Walk(0x7cb848, 0xc82b76bf40, 0x7cb8a0, 0xc820b82c00)
	/usr/local/go/src/go/ast/walk.go:331 +0x1f7d
go/ast.walkDeclList(0x7cb848, 0xc82b76bf40, 0xc820b82c40, 0x4, 0x4)
	/usr/local/go/src/go/ast/walk.go:38 +0xd5
go/ast.Walk(0x7cb848, 0xc82b76bf40, 0x6d6550, 0xc8204c1b00)
	/usr/local/go/src/go/ast/walk.go:353 +0x29b9
github.com/mvdan/interfacer.checkPkg(0xc8200a00c0, 0xc82084a8c0, 0x64c6f0, 0xc820030010)
	/Users/bep/go/src/github.com/mvdan/interfacer/check.go:144 +0x17b
github.com/mvdan/interfacer.CheckArgs(0xc82000a1d0, 0x1, 0x1, 0x64c6f0, 0xc820030010, 0x0, 0x0, 0x0)
	/Users/bep/go/src/github.com/mvdan/interfacer/check.go:132 +0x44d
main.main()
	/Users/bep/go/src/github.com/mvdan/interfacer/cmd/interfacer/main.go:20 +0xa4

```

**Comment by mvdan** [comment]
Thanks! Will look into it.
