### ISSUE TITLE
Panics on github.com/tucnak/kamu

### ISSUE THREAD

**Issue by tucnak** [mvdan/interfacer#7]
```
$ go version
go version go1.5 darwin/amd64
$ interfacer ./...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x7f241]

goroutine 1 [running]:
github.com/mvdan/interfacer.orderedPkgs(0x82050a840, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/tucnak/Development/gopher/src/github.com/mvdan/interfacer/check.go:105 +0x321
github.com/mvdan/interfacer.CheckArgs(0x820508030, 0x1, 0x1, 0x88206906c8, 0x82051e008, 0x0, 0x0, 0x0)
	/Users/tucnak/Development/gopher/src/github.com/mvdan/interfacer/check.go:123 +0x1c8
main.main()
	/Users/tucnak/Development/gopher/src/github.com/mvdan/interfacer/cmd/interfacer/main.go:20 +0xa4
```

**Comment by mvdan** [comment]
I spotted this roughly an hour ago after updating my `go/loader` and fixed it in https://github.com/mvdan/interfacer/commit/6384c3c26188ca9dd9285308a79035018f82c30c. So if you pull and rebuild, it should work for you.

**Comment by mvdan** [comment]
For all of you coming from duplicate issues: make sure you have the latest interfacer and the latest `golang.org/x/tools`:

    go get -u -v github.com/mvdan/interfacer
